In [86]:
%matplotlib inline
import pandas as pd
import mplfinance as mpf


file = 'GBPJPY_historical_data.csv'
data = pd.read_csv(file)

data.drop(["Unnamed: 7"], axis = 1, inplace = True)

data

,Date,Open,High,Low,Close,Change(Pips),Change(%)
0,07/07/2023 00:00,183.437,183.5430,183.14000,183.419,-1.8,-0.01
1,07/06/2023 23:00,183.524,183.6000,183.32000,183.441,-8.3,-0.05
2,07/06/2023 22:00,183.486,183.5590,183.44700,183.552,6.6,0.04
3,07/06/2023 21:00,183.515,183.6061,183.32900,183.480,-3.5,-0.02
4,07/06/2023 20:00,183.610,183.6200,183.46565,183.500,-11.0,-0.06
...,...,...,...,...,...,...,...
993,05/23/2023 08:00,171.675,171.7540,171.26000,171.640,-3.5,-0.02
994,05/23/2023 07:00,172.121,172.1300,171.62000,171.640,-48.1,-0.28
995,05/23/2023 06:00,172.231,172.3100,171.96000,172.111,-12.0,-0.07
996,05/23/2023 05:00,172.121,172.2720,172.08000,172.229,10.8,0.06
997,05/23/2023 04:00,172.385,172.3900,172.00000,172.122,-26.3,-0.15

In [93]:
# Convert the "Date" column to datetime format
data['Date'] = pd.to_datetime(data['Date'])

# Create separate columns for date and time
data['Date_only'] = data['Date'].dt.date
data['Time'] = data['Date'].dt.time

# Drop the original "Date" column
data.drop('Date', axis=1, inplace=True)

data

KeyError: 'Date'